### ISSUE TITLE
WORK CHECKLIST

### ISSUE THREAD

**Issue by pvmhae-alcoran** [pvmhae-alcoran/E-E-Exam#5]
WEEK 1

- [x] Create a Group Name
- [x] Create a Repository (c/o Team Leader Alcoran)
- [x] Distribution of Tasks and Roles (initial)
- [x] Fill out the Google Form

WEEK 2

- [x] Decide on the library/package to be used in developing the codes and the UI
- [x] Decide on the User Interface Design of the Project
- [x] Trials on the UI Design
- [x] Initial Stopwatch Codes
- [x] Developing better codes
- [x] Discussion of errors
- [x] Start of Documentation (c/o Danlag)

WEEK 3
 
- [x] Finalize the codes from the last discussions
- [x] Record the discussion
- [x] Check the codes
- [x] Finalize the codes
- [x] Finalize the documentation (2-3 minutes only)
- [x] Ready for SUBMISSION

LASTLY

- [x] Always ask for guidance and wisdom from Above
- [x] No pressure, just enjoy!

Philippians 4:13 "I can do all things through CHRIST who strengthens me"
